const MODELS = require("./creepModels");

let parameters = {
  // Room status
  ROOM_NUMBER: "W35N43",
  // HARVESTERS
  HARVESTER_CURRENT_MODEL: MODELS.HARVESTER_400_FAST,
  HARVESTER_TEAM_SIZE: 3,
  HARVESTER_SOURCE_INDEX: 0,
  // MINERS
  MINER_CURRENT_MODEL: MODELS.MINER_700,
  MINER_TEAM_SIZE: 1,
  MINER_SOURCE_INDEX: 0,
  // BUILDERS
  BUILDER_CURRENT_MODEL: MODELS.BUILDER_350_LARGE,
  BUILDER_TEAM_SIZE: 1,
  BUILDER_SOURCE_INDEX: 1,
  // UPGRADERS
  UPGRADER_TEAM_SIZE: 1,
  UPGRADER_CURRENT_MODEL: MODELS.UPGRADER_600,
  UPGRADER_ENERGY_SOURCE: "source",
  UPGRADER_SOURCE_INDEX: 0,
  // REPAIRERS
  REPAIRER_TEAM_SIZE: 4,
  REPAIRER_CURRENT_MODEL: MODELS.REPAIRER_400,
  REPAIRER_SOURCE_INDEX: 1,
  REPAIR_PRIORITY: "none",
  REPAIR_HITS_THRESHOLD_RATIO: 1 / 4,
};

module.exports = parameters;
